runtime:
  cache_dir: ./.cache/antora

site:
  title: Accelerate New App Development
  start_page: acc-new-app-dev-guides:m1:intro.adoc

content:
  sources:
    - url: .
      start_path: docs

asciidoc:
  attributes:
    experimental: true
    page-pagination: true

ui:
  bundle:
    url: ./ui/ui-bundle.zip
  supplemental_files: ./ui/supplemental-ui

output:
  dir: ./site
